### ISSUE TITLE
files since 03/09 are blank

### ISSUE THREAD

**Issue by sarjarapu** [tigger0jk/ark-invest-scraper#2]
the fund holdings are blank potentially because the website added check for user agent.

**Comment by tigger0jk** [comment]
Thanks for the report! Yup - added an honest user-agent and pulling again successfully. Thankfully they aren't blocking everything.

**Comment by MichaelDeBoey** [comment]
It's there again: https://github.com/tigger0jk/ark-invest-scraper/commit/59310e1817f73bf7087515e533bbcb07cf57d6cc

**Comment by MichaelDeBoey** [comment]
@tigger0jk It's there again: https://github.com/tigger0jk/ark-invest-scraper/commit/59310e1817f73bf7087515e533bbcb07cf57d6cc

**Comment by tigger0jk** [comment]
After some testing I believe they are blocking "github" in the user agent string now. I am taking this as a sign that they are getting lots of spammy requests (which this repo is partially responsible for) that they want to block. I am therefore reducing the times my action runs from 3 times per hour (72 per day) to twice per day.

Now that this scraper has cleaned up its act in terms of requests, I updated my particular string to be uppercase "Github". This is a bit scummy since I'm doing it intentionally to dodge the filter. However I do believe that I have changed my ways and what I'm doing is now very reasonable. Also I can't say if they are trying explicitly to block this repo or not, but it is a definite possibility.

Their current https://ark-invest.com/robots.txt doesn't indicate to me that they don't want these files scraped:
```
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
```

If they update their filter to block the new agent, that seems like a pretty irrefutable sign that they don't appreciate this traffic. If that happens I think I would reach out to them and ask if they really don't want a history of these files scraped. (It seems like good information about their fund they would want to be publicly available!).

Obviously I could update the agent to emulate a real browser, but that doesn't seem like the ethical scraping approach.
